const mongoose = require('mongoose')

const farmerInfoSchema = new mongoose.Schema({
  profilePic:String,
  userId:{
    type:String,
    required:true
  },
  farmId:String,
  perinfo:{
  firstName:{
    type:String,
    required:true
  },
  middleName:{
    type:String,
    required:true
  },
  lastName:{
    type:String,
    required:true
  },
  adhar :{
    type:String,
    required:true
  },
  gender:{
    type:String,
    required:true
  },
  district:{
    type:String,
    required:true
  },
  taluko:{
    type:String,
    required:true
  },
  village:{
    type:String,
    required:true
  },
  homeAddrs:{
    type:String,
    required:true
  },
  dob:{
    type:String,
    required:true
  },
  pincode:String,
  },
  comminfo:{
    mobileNumber:{
     type:String,
     required: true  
    },
    email:{
     type:String,
    }
 },
 farmInfo:[{
    title:String,
    shape:String,
    surveyNum:{
        type:String,
        required:true
    },
    upin:{
        type:String,
    }
}],
  yeildInfo:{
    landTitle:{
        type:String,
        required:true
    },
    year:{
        type:String,
        required:true
    },
    cropName:{
        type:String,
        required:true
    },
    quintity:{
        type:String,
        required:true
    },
    unit:{
        type:String,
        required:true
    },
    totalPrice:{
        type:String,
        required:true
    },
    cropType:{
        type:String,
        required:true
    },
    harvestTech:{
        type:String,
        required:true
    },
  },
  bankInfo:{
    bankName:{
        type:String,
        required:true
    },
    branchName:{
        type:String,
        required:true
    },
    taluka:{
        type:String,
        required:true
    },
    accountNumber:{
        type:String,
        required:true
    },
    ifsc:{
        type:String,
        required:true
    }
  } 
}) 




module.exports =  mongoose.model("farmerInfo",farmerInfoSchema);


